on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - main

jobs:
  newman:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the repository to access files

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2  # Set up Node.js
      #   with:
      #     node-version: '14'  # Specify the Node.js version
      # - name: Install Newman and reporters
      #   run: |
      #     npm install -g newman  # Install Newman globally
          # npm install -g newman-reporter-cli newman-reporter-html  # Install CLI and HTML reporters

      - name: Run Newman tests
        run: |
          # Run Newman with the collection and environment file from the repo
          newman run ./ProductsModule.postman_collection.json -d ./product_data.json -g ./workspace.postman_globals.json --reporters cli,html --reporter-html-export newman-report.html
      - name: List directory to confirm report file exists
        run: |
          echo "Listing directory contents"
          dir  # On Windows, `dir` will list files in the current directory
          
      # - name: Upload Newman HTML report
      #   uses: actions/upload-artifact@v2  # Upload the report as an artifact
      #   with:
      #     name: newman-report
      #     path: newman-report.html  # Path to the generated report

      - name: Post status if tests fail
        if: ${{ failure() }}  # Only run if tests fail
        run: |
          echo "Test run failed. Please check the Newman report for details."
